version: '3.8'

services:
  server:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 8000:8000
    depends_on:
      - db
    command: bash -c "alembic upgrade head && uvicorn blog_api.main:app --host 0.0.0.0 --port 8000 --reload"
    restart: always

  db:
    image: postgres:13-alpine
    ports:
      - 5433:5432
    environment:
      POSTGRES_PASSWORD: password
      POSTGRES_USER: postgres
      POSTGRES_DB: test
    restart: always

