version: '3.8'

services:
  server:
    build:
      context: ./blog_api
      dockerfile: ../Dockerfile
    volumes:
      - ./blog_api/:/blog_api/
    ports:
      - 8000:8000
    depends_on:
      - db

  db:
    image: postgres:13-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    ports:
      - 5432:5432

volumes:
  postgres_data: